# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Featherlite"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.119.0"

[author]
name = "Manuel Schönlaub"
homepage = "https://github.com/mschoenlaub/"

[original]
  name = "Christian Engel"
  homepage = "https://github.com/chringel21/"
  repo = "https://github.com/chringel21/chringel-hugo-theme"

